Nginx update to ver 1.13.3
skilld-labs/skilld-docker-nginx pull request #11
Opened 2017-08-03 08:18 UTC by gaydabura

2017-08-03 14:40 UTC, gaydabura commented
updated PR. please review it

2017-08-03 14:55 UTC, andypost requested changes
- You make too many layers in image
- remove bash
- no reason to configure volume&workdir with env
- add back proxy options

2017-08-03 14:55 UTC, andypost commented on Dockerfile
> +        bash \
please remove bash, alpine has busybox with `ash`

2017-08-03 14:55 UTC, andypost commented on Dockerfile
> +RUN sed -i "s/{{ NGINX_FASTCGI_READ_TIMEOUT }}/${NGINX_FASTCGI_READ_TIMEOUT}/" /etc/nginx/nginx.conf
all this RUNs should be oneliner to have less layers in image

2017-08-03 14:55 UTC, andypost commented on Dockerfile
> +VOLUME ${NGINX_DOCUMENT_ROOT}
I see no reason to make it configurable with ENV because it will be set in stone in image anyway

2017-08-03 14:55 UTC, andypost commented on drupal8.conf
> -        proxy_set_header X-Forwarded-Proto $scheme;
why that removed?

for every project we use following things to pass
```
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
```

2017-08-03 14:55 UTC, andypost commented on Dockerfile
> +ENV NGINX_FASTCGI_BUFFERS "16 32k"
are you sure that 16 buffers enough?

2017-08-04 12:10 UTC, gaydabura commented on Dockerfile
> +ENV NGINX_FASTCGI_BUFFERS "16 32k"
by default `8 4k` and its value you can change locally for your project

2017-08-04 12:19 UTC, andypost requested changes
Still require to minimize number of layers inside image

2017-08-04 12:19 UTC, andypost commented on drupal8.conf
> +}
(

2017-08-04 12:19 UTC, andypost commented on Dockerfile
> +RUN sed -i "s/{{ NGINX_FASTCGI_BUFFERS }}/${NGINX_FASTCGI_BUFFERS}/;s/{{ NGINX_FASTCGI_BUFFER_SIZE }}/${NGINX_FASTCGI_BUFFER_SIZE}/;s/{{ NGINX_FASTCGI_READ_TIMEOUT }}/${NGINX_FASTCGI_READ_TIMEOUT}/"
still lots of layers(

2017-08-04 12:19 UTC, andypost commented on README.md
> +## Environment Variables
actually it is not true, because this vars applied only once at container build time

2018-02-19 17:53 UTC, alexkras commented
Need to review last changes

2018-11-14 21:27 UTC, uzlov commented on drupal8.conf
> +        proxy_set_header Upgrade $http_upgrade;
lines 17-23 for proxying of websockets

2021-03-17 15:48 UTC, andypost commented
I think it outdated enough

2021-03-17 15:48 UTC, closed without merging